spring.application.name=Historial-Service

spring.datasource.url=jdbc:mysql://localhost:3306/Historial_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8084